
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odhfdzormqlbfpeibgjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kaGZkem9ybXFsYmZwZWliZ2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzU2MjYsImV4cCI6MjA1OTk1MTYyNn0.l9DNyNz-l40prX1d2t1TBZuEiwndL4874n7if-PatMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
  }
});
